### ISSUE TITLE
Pypi naming conflict

### ISSUE THREAD

**Issue by CrackerJackMack** [salimane/rediscluster-py#11]
Looks like two different projects have identical names in the python module name space.

I'm crossing linking the issues so that the two developers could come to an agreement on module naming.  Not that it would happen often, but the two modules can't co-exist in the same python environment.
## The issue

Both modules install to `site-packages/rediscluster` which while not likely, is still a conflict.

Grokzen/redis-py-cluster/issues/150

**Comment by salimane** [comment]
This repo is deprecated. Please use the official Redis library.
