### ISSUE TITLE
ImportError: Cannot import name b

### ISSUE THREAD

**Issue by MuppetPasta** [salimane/rediscluster-py#13]
`from redis._compat import b, unicode, bytes, long, basestring`
redis-py as of version 3.0.0 no longer exposes b(). I've submitted MR #12 for this
temporary workaround is to pin redis==2.10.6

**Comment by gcd0318** [comment]
also bytes can not import, which is not supported any more

**Comment by salimane** [comment]
@MuppetPasta @gcd0318 please use the official Redis library, this library is outdated and not maintained anymore
