### ISSUE TITLE
 dictkeys, dictvalues no longer supported in current redis version

### ISSUE THREAD

**Issue by gbenmartin** [salimane/rediscluster-py#3]
install will not complete because cluster_client.py can't import dictkeys/dictvalues from redis because they are now dictionary iterator objects -  called 'iterkeys' and 'itervalues' now - in the current version of redis. I had to install an old commit from redis to get the rediscluster install to complete.

https://github.com/andymccurdy/redis-py/blob/master/redis/_compat.py#L16-L17

**Comment by KimJongyouly** [comment]
hi solve it.... 

enviroment 
 - python version 2.7.6
 - redis version 2.10.5
 - rediscluster version 0.5.3

bug : from redis._compat.dictkeys 

source download and fix file "/rediscluster-0.5.3/rediscluster/cluster_client.py"

line #5 from redis._compat import (b, iteritems, dictkeys, dictvalues, basestring, bytes)
from redis._compat import (b, iteritems, basestring, bytes)
from redis._compat import iterkeys as dictkeys
from redis._compat import itervalues as  dictvalues

and then 

python setup.py install
