### ISSUE TITLE
Redis Cluster Spec compliance

### ISSUE THREAD

**Issue by CloudMarc** [salimane/rediscluster-py#7]
Redis server 3.0 supports clustering.  

This code does not comply with the redis cluster spec - http://redis.io/topics/cluster-spec

In particular, it does not handle MOVED and ASK - https://github.com/salimane/rediscluster-py/search?utf8=%E2%9C%93&q=moved&type=Code

cc @antirez

**Comment by salimane** [comment]
@CloudMarc this library was built before the release of redis 3, thus not supporting the new apis. I would definitely welcome a PR to comply to the redis cluster spec.
Thanks

**Comment by CloudMarc** [comment]
Hi @salimane - I think the point I was trying to make is that people will be confused when they find this and attempt to use it with Redis Cluster.  Perhaps there could be a note at the front of the Readme saying this predates Redis Cluster and does not yet support the Redis Cluster Protocol.  Also, it's my second invitation to build client-side Redis Cluster support today ;)  Cheers

**Comment by salimane** [comment]
@CloudMarc I fully support your point and a PR for the readme would also be appreciated :)
