### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by svenstaro** [salimane/rediscluster-py#9]
Hi, the last release was 3 years ago. Please push a new version onto pypi.

**Comment by salimane** [comment]
@svenstaro, this repo is for pre redis 3.0 . are you aware of that ?

**Comment by svenstaro** [comment]
Oh, no I'm not. I thought it was a way to backport that functionality to redis 2.x :/

**Comment by salimane** [comment]
Yep this is for redis 2.x
